FROM node:20-slim AS build

WORKDIR /app
COPY srv/web /app/srv/web
WORKDIR /app/srv/web
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY docker/nginx-http.conf /etc/nginx/spacegate/nginx-http.conf
COPY docker/nginx-tls.conf /etc/nginx/spacegate/nginx-tls.conf
COPY docker/40-spacegate-nginx-mode.sh /docker-entrypoint.d/40-spacegate-nginx-mode.sh
RUN chmod +x /docker-entrypoint.d/40-spacegate-nginx-mode.sh
COPY --from=build /app/srv/web/dist /usr/share/nginx/html

EXPOSE 80 443
