FROM node:20-slim AS build

WORKDIR /app
COPY srv/web /app/srv/web
WORKDIR /app/srv/web
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/srv/web/dist /usr/share/nginx/html

EXPOSE 80
