#!/usr/bin/env python3
from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import os
import sqlite3
import tarfile
import time
from pathlib import Path
from typing import Any

import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "srv" / "api"))

from app.simulation_scene_contract import (  # noqa: E402
    SIMULATION_SCENE_ARTIFACT_VERSION as SCENE_MATERIALIZER_VERSION,
)


FREEZER_VERSION = "simulation_scene_freezer_v1"


def canonical_json(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_json(path: Path, value: Any) -> None:
    temporary = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    temporary.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def validate_scene(path: Path, *, build_id: str) -> tuple[bytes, dict[str, Any]]:
    compressed = path.read_bytes()
    try:
        payload = json.loads(gzip.decompress(compressed))
    except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise ValueError(f"invalid scene artifact: {path}") from exc
    materialization = payload.get("materialization")
    if not isinstance(materialization, dict):
        raise ValueError(f"scene lacks materialization metadata: {path}")
    if materialization.get("build_id") != build_id:
        raise ValueError(f"scene build identity mismatch: {path}")
    if materialization.get("materializer_version") != SCENE_MATERIALIZER_VERSION:
        raise ValueError(f"scene materializer version mismatch: {path}")
    if not materialization.get("deterministic"):
        raise ValueError(f"scene was not generated by deterministic materializer: {path}")
    return compressed, payload


def required_system_ids(public_read_db: Path) -> list[int]:
    uri = f"file:{public_read_db.resolve()}?mode=ro&immutable=1"
    con = sqlite3.connect(uri, uri=True)
    try:
        return [
            int(row[0])
            for row in con.execute(
                """
                SELECT system_id
                FROM systems
                WHERE scene_representation='full_scene'
                ORDER BY system_id
                """
            )
        ]
    finally:
        con.close()


def run(args: argparse.Namespace) -> dict[str, Any]:
    started = time.perf_counter()
    state_dir = Path(args.state_dir).resolve()
    build_id = args.build_id
    public_read_dir = (
        Path(args.public_read_dir).resolve()
        if args.public_read_dir
        else state_dir / "derived" / "public_read" / build_id
    )
    public_read_db = public_read_dir / "public_read.sqlite"
    cache_dir = (
        Path(args.cache_dir).resolve()
        if args.cache_dir
        else state_dir / "cache" / "simulation_scenes" / build_id
    )
    output_dir = (
        Path(args.output_dir).resolve()
        if args.output_dir
        else state_dir / "derived" / "simulation_scenes" / build_id
    )
    if not public_read_db.is_file():
        raise SystemExit(f"missing public-read database: {public_read_db}")
    required = required_system_ids(public_read_db)
    if not required:
        raise SystemExit("public-read policy selected no full scenes")

    entries: list[dict[str, Any]] = []
    compressed_payloads: dict[int, bytes] = {}
    missing: list[int] = []
    invalid: list[dict[str, Any]] = []
    validation_started = time.perf_counter()
    for system_id in required:
        path = cache_dir / f"system_{system_id}.json.gz"
        if not path.is_file():
            missing.append(system_id)
            continue
        try:
            compressed, payload = validate_scene(path, build_id=build_id)
        except ValueError as exc:
            invalid.append({"system_id": system_id, "error": str(exc)})
            continue
        compressed_payloads[system_id] = compressed
        entries.append(
            {
                "system_id": system_id,
                "path": f"scenes/system_{system_id}.json.gz",
                "bytes": len(compressed),
                "sha256": sha256_bytes(compressed),
                "scene_schema_version": payload.get("schema_version"),
            }
        )
    validation_seconds = time.perf_counter() - validation_started
    if missing or invalid:
        raise SystemExit(
            f"scene coverage incomplete: missing={len(missing)} invalid={len(invalid)}"
        )

    artifact_manifest = {
        "schema_version": "spacegate.simulation_scene_frozen_set.v1",
        "freezer_version": FREEZER_VERSION,
        "scene_materializer_version": SCENE_MATERIALIZER_VERSION,
        "build_id": build_id,
        "required_count": len(required),
        "scene_count": len(entries),
        "total_scene_bytes": sum(row["bytes"] for row in entries),
        "entries": entries,
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    archive = output_dir / "simulation_scenes.tar.gz"
    previous_archive_sha256 = sha256_file(archive) if archive.is_file() else None
    temporary = archive.with_name(f".{archive.name}.tmp.{os.getpid()}")
    archive_started = time.perf_counter()
    try:
        with temporary.open("wb") as raw:
            with gzip.GzipFile(
                filename="",
                mode="wb",
                fileobj=raw,
                compresslevel=6,
                mtime=0,
            ) as compressed_archive:
                with tarfile.open(
                    fileobj=compressed_archive,
                    mode="w|",
                    format=tarfile.PAX_FORMAT,
                ) as tar:
                    manifest_bytes = canonical_json(artifact_manifest)
                    manifest_info = tarfile.TarInfo("manifest.json")
                    manifest_info.size = len(manifest_bytes)
                    manifest_info.mtime = 0
                    manifest_info.mode = 0o664
                    manifest_info.uid = manifest_info.gid = 0
                    manifest_info.uname = manifest_info.gname = ""
                    tar.addfile(manifest_info, io.BytesIO(manifest_bytes))
                    for entry in entries:
                        system_id = int(entry["system_id"])
                        content = compressed_payloads[system_id]
                        info = tarfile.TarInfo(str(entry["path"]))
                        info.size = len(content)
                        info.mtime = 0
                        info.mode = 0o664
                        info.uid = info.gid = 0
                        info.uname = info.gname = ""
                        tar.addfile(info, io.BytesIO(content))
        os.replace(temporary, archive)
    finally:
        temporary.unlink(missing_ok=True)

    archive_sha256 = sha256_file(archive)
    archive_seconds = time.perf_counter() - archive_started
    report = {
        **artifact_manifest,
        "archive": {
            "path": archive.name,
            "bytes": archive.stat().st_size,
            "sha256": archive_sha256,
        },
        "verification": {
            "status": "pass",
            "missing_count": 0,
            "invalid_count": 0,
            "duplicate_system_count": len(required) - len(set(required)),
            "previous_archive_sha256": previous_archive_sha256,
            "deterministic_rebuild_match": (
                previous_archive_sha256 == archive_sha256
                if previous_archive_sha256 is not None
                else None
            ),
        },
        "performance": {
            "validation_seconds": round(validation_seconds, 6),
            "archive_seconds": round(archive_seconds, 6),
            "total_seconds": round(time.perf_counter() - started, 6),
        },
    }
    atomic_json(output_dir / "manifest.json", report)
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Freeze a verified warmed scene set into one deterministic archive."
    )
    parser.add_argument("--build-id", required=True)
    parser.add_argument(
        "--state-dir",
        default=os.getenv("SPACEGATE_STATE_DIR", "/data/spacegate/state"),
    )
    parser.add_argument("--public-read-dir")
    parser.add_argument("--cache-dir")
    parser.add_argument("--output-dir")
    return parser.parse_args()


def main() -> int:
    report = run(parse_args())
    print(
        json.dumps(
            {
                "status": report["verification"]["status"],
                "build_id": report["build_id"],
                "scene_count": report["scene_count"],
                "total_scene_bytes": report["total_scene_bytes"],
                "archive": report["archive"],
                "deterministic_rebuild_match": report["verification"][
                    "deterministic_rebuild_match"
                ],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
