#!/usr/bin/env python3
"""Independently verify and reproduce the stellar-orbit endpoint bridge."""

from __future__ import annotations

import argparse,json,resource,shutil,tempfile,time
from datetime import datetime,timezone
from pathlib import Path
from typing import Any
import duckdb
import compile_e7_stellar_orbit_endpoint_bridge as compiler

DEFAULT_SCRATCH=Path("/mnt/space/spacegate")
PRODUCTS={
  "stellar_orbit_endpoint_bindings.parquet":"endpoints",
  "stellar_orbit_group_memberships.parquet":"group_memberships",
  "stellar_orbit_relation_bindings.parquet":"relations",
}

def audit(policy_path:Path,state:Path,manifest_path:Path)->dict[str,Any]:
  started=time.monotonic();policy=compiler.load_object(policy_path);compiler.validate_policy(policy);manifest=compiler.load_object(manifest_path);checks={"manifest_status_pass":manifest.get("status")=="pass","manifest_schema":manifest.get("schema_version")=="spacegate.e7_stellar_orbit_endpoint_bridge_manifest.v4","stability_databases_not_opened":manifest.get("stability_databases_opened")==[],"policy_sha256_match":manifest.get("policy_sha256")==compiler.file_sha256(policy_path),"compiler_sha256_match":manifest.get("compiler_sha256")==compiler.file_sha256(Path(compiler.__file__).resolve())};inputs=compiler.resolve_inputs(policy,state);paths={}
  for filename,table in PRODUCTS.items():
    path=manifest_path.parent/filename;entry=(manifest.get("products") or {}).get(filename) or {};paths[table]=path;prefix=filename.removesuffix(".parquet");checks[f"{prefix}_exists"]=path.is_file();checks[f"{prefix}_bytes_match"]=path.is_file() and path.stat().st_size==entry.get("bytes");checks[f"{prefix}_sha256_match"]=path.is_file() and compiler.file_sha256(path)==entry.get("sha256");checks[f"{prefix}_byte_exact"]=entry.get("determinism")=="byte_exact"
  con=duckdb.connect();metrics={}
  try:
    for table,path in paths.items():con.execute(f"CREATE VIEW {table} AS SELECT * FROM read_parquet({compiler.sql_literal(path)})")
    con.execute(f"ATTACH {compiler.sql_literal(inputs['components'])} AS component_scope (READ_ONLY)");con.execute(f"ATTACH {compiler.sql_literal(inputs['hierarchy'])} AS hierarchy (READ_ONLY)");con.execute(f"CREATE VIEW selected_relations AS SELECT * FROM read_parquet({compiler.sql_literal(inputs['relations'])})")
    scalar=lambda sql:int(con.execute(sql).fetchone()[0] or 0)
    counts={"endpoints":scalar("SELECT count(*) FROM endpoints"),"endpoints_accepted":scalar("SELECT count(*) FROM endpoints WHERE binding_status='accepted'"),"endpoints_missing_runtime_leaf":scalar("SELECT count(*) FROM endpoints WHERE binding_reason='runtime_leaf_missing'"),"endpoints_ambiguous_source_case":scalar("SELECT count(*) FROM endpoints WHERE binding_reason='exact_source_label_collision'"),"relations":scalar("SELECT count(*) FROM relations"),"relations_runtime_eligible":scalar("SELECT count(*) FROM relations WHERE runtime_eligible"),"relations_one_endpoint_unresolved":scalar("SELECT count(*) FROM relations WHERE binding_status='one_endpoint_unresolved'"),"relations_both_endpoints_unresolved":scalar("SELECT count(*) FROM relations WHERE binding_status='both_endpoints_unresolved'"),"preferred_relations":scalar("SELECT count(*) FROM relations WHERE preferred_simulation_solution_id IS NOT NULL"),"preferred_relations_runtime_eligible":scalar("SELECT count(*) FROM relations WHERE preferred_simulation_solution_id IS NOT NULL AND runtime_eligible"),"preferred_relations_one_endpoint_unresolved":scalar("SELECT count(*) FROM relations WHERE preferred_simulation_solution_id IS NOT NULL AND binding_status='one_endpoint_unresolved'"),"preferred_relations_both_endpoints_unresolved":scalar("SELECT count(*) FROM relations WHERE preferred_simulation_solution_id IS NOT NULL AND binding_status='both_endpoints_unresolved'"),"containment_promotions":scalar("SELECT count(*) FROM relations WHERE canonical_containment"),"group_endpoints_accepted":scalar("SELECT count(*) FROM endpoints WHERE endpoint_kind='group' AND binding_status='accepted'"),"group_memberships":scalar("SELECT count(*) FROM group_memberships"),"preferred_or_source_period_relations_runtime_eligible":scalar("SELECT count(*) FROM relations WHERE simulation_eligible")};expected={key:int(value) for key,value in policy["acceptance"].items()}
    scalars={"acceptance_count_delta":sum(abs(counts.get(key,-1)-value) for key,value in expected.items()),"manifest_count_delta":sum(abs(counts.get(key,-1)-int(value)) for key,value in (manifest.get("verification",{}).get("counts") or {}).items()),"duplicate_endpoints":scalar("SELECT count(*) FROM (SELECT source_component_key FROM endpoints GROUP BY 1 HAVING count(*)<>1)"),"duplicate_group_memberships":scalar("SELECT count(*) FROM (SELECT group_runtime_component_key,child_runtime_component_key FROM group_memberships GROUP BY ALL HAVING count(*)<>1)"),"duplicate_relations":scalar("SELECT count(*) FROM (SELECT relation_id FROM relations GROUP BY 1 HAVING count(*)<>1)"),"missing_source_component":scalar("SELECT count(*) FROM endpoints e LEFT JOIN component_scope.msc_component_entities c USING(source_component_key) WHERE c.component_entity_id IS NULL"),"missing_selected_relation":scalar("SELECT count(*) FROM relations r LEFT JOIN selected_relations s USING(relation_id) WHERE s.relation_id IS NULL"),"accepted_leaf_missing_hierarchy_leaf":scalar("SELECT count(*) FROM endpoints e LEFT JOIN hierarchy.hierarchy_nodes h USING(hierarchy_node_key) WHERE e.binding_status='accepted' AND e.endpoint_kind='leaf' AND h.hierarchy_node_key IS NULL"),"group_containment_promotions":scalar("SELECT count(*) FROM group_memberships WHERE canonical_containment"),"unaccepted_runtime_keys":scalar("SELECT count(*) FROM endpoints WHERE binding_status<>'accepted' AND runtime_component_key IS NOT NULL"),"invented_runtime_components":scalar("SELECT count(*) FROM endpoints WHERE creates_runtime_component"),"unresolved_runtime_edges":scalar("SELECT count(*) FROM relations WHERE NOT runtime_eligible AND creates_runtime_edge"),"invalid_simulation_eligibility":scalar("SELECT count(*) FROM relations WHERE simulation_eligible AND (NOT runtime_eligible OR (preferred_simulation_solution_id IS NULL AND source_period_days IS NULL))"),"endpoint_descendant_overlap":scalar("SELECT count(*) FROM relations WHERE runtime_eligible AND list_has_any(primary_descendant_leaf_keys_json::VARCHAR[],secondary_descendant_leaf_keys_json::VARCHAR[])"),"endpoint_system_mismatch":scalar("SELECT count(*) FROM relations r JOIN endpoints p ON p.endpoint_binding_id=r.primary_endpoint_binding_id JOIN endpoints s ON s.endpoint_binding_id=r.secondary_endpoint_binding_id WHERE p.canonical_system_stable_object_key<>r.canonical_system_stable_object_key OR s.canonical_system_stable_object_key<>r.canonical_system_stable_object_key")};checks.update({key:value==0 for key,value in scalars.items()});metrics={"counts":counts,"scalar_checks":scalars}
  finally:con.close()
  failures=sorted(key for key,value in checks.items() if not value);return {"schema_version":"spacegate.e7_stellar_orbit_endpoint_bridge_verification.v1","generated_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),"build_id":manifest.get("build_id"),"status":"pass" if not failures else "fail","checks":checks,"failing_checks":failures,"metrics":metrics,"wall_seconds":round(time.monotonic()-started,6)}

def reproduce(policy_path:Path,state:Path,manifest_path:Path,scratch_parent:Path)->dict[str,Any]:
  started=time.monotonic();cpu=time.process_time();reference=compiler.load_object(manifest_path);scratch=Path(tempfile.mkdtemp(prefix="e7-orbit-endpoint-reproduction-",dir=scratch_parent))
  try:
    rebuilt=compiler.compile_bridge(policy_path,state,scratch/"artifacts",link_into_state=False);rebuilt_manifest=scratch/"artifacts"/rebuilt["build_id"]/"manifest.json";independent=audit(policy_path,state,rebuilt_manifest);checks={"build_id_match":rebuilt.get("build_id")==reference.get("build_id"),"inputs_match":rebuilt.get("inputs")==reference.get("inputs"),"products_match":rebuilt.get("products")==reference.get("products"),"verification_match":rebuilt.get("verification")==reference.get("verification"),"independent_verification_pass":independent.get("status")=="pass"}
  finally:shutil.rmtree(scratch,ignore_errors=True)
  checks["scratch_removed"]=not scratch.exists();failures=sorted(key for key,value in checks.items() if not value);usage=resource.getrusage(resource.RUSAGE_SELF);return {"schema_version":"spacegate.e7_stellar_orbit_endpoint_bridge_reproduction.v1","generated_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),"build_id":reference.get("build_id"),"status":"pass" if not failures else "fail","checks":checks,"failing_checks":failures,"rebuild_performance":rebuilt.get("performance"),"total_timing":{"wall_seconds":round(time.monotonic()-started,6),"cpu_seconds":round(time.process_time()-cpu,6),"peak_rss_kib":int(usage.ru_maxrss)}}

def main()->int:
  parser=argparse.ArgumentParser(description=__doc__);parser.add_argument("--policy",type=Path,default=compiler.DEFAULT_POLICY);parser.add_argument("--state-dir",type=Path,default=compiler.DEFAULT_STATE);parser.add_argument("--manifest",type=Path,required=True);parser.add_argument("--reproduce",action="store_true");parser.add_argument("--scratch-parent",type=Path,default=DEFAULT_SCRATCH);parser.add_argument("--report",type=Path);args=parser.parse_args();report=reproduce(args.policy.resolve(),args.state_dir.resolve(),args.manifest.resolve(),args.scratch_parent.resolve()) if args.reproduce else audit(args.policy.resolve(),args.state_dir.resolve(),args.manifest.resolve());rendered=json.dumps(report,indent=2,sort_keys=True)+"\n"
  if args.report:args.report.parent.mkdir(parents=True,exist_ok=True);args.report.write_text(rendered,encoding="utf-8")
  print(rendered,end="");return 0 if report["status"]=="pass" else 1

if __name__=="__main__":raise SystemExit(main())
